common:
  log_level: error
  assume_yes: true
operations:
  - command: ["workflow"]
    with: &workflow_defaults
      roots:
        - .
      assume_yes: true
  - command: ["remote", "update-protocol"]
    with: &conversion_defaults
      roots:
        - .
      assume_yes: true
      from: https
      to: ssh
  - command: ["remote", "update-to-canonical"]
    with: &remote_defaults
      roots:
        - .
      assume_yes: true
      owner: canonical
  - command: ["default"]
    with: &migration_defaults
      roots:
        - .
      debug: false
      targets:
        - remote_name: origin
          target_branch: master
          push_to_remote: false
          delete_source_branch: false
workflow:
  - step:
      command: ["remote", "update-protocol"]
      with:
        <<: *conversion_defaults
  - step:
      command: ["remote", "update-to-canonical"]
      with:
        <<: *remote_defaults
  - step:
      command: ["default"]
      with:
        <<: *migration_defaults
  - step:
      command: ["audit", "report"]
      with:
        output: ./reports/audit-latest.csv
