package shared

// Event code catalogue shared across repository executors and workflow logging.
const (
	EventCodeRepoSwitched             = "REPO_SWITCHED"
	EventCodeRepoDirty                = "REPO_DIRTY"
	EventCodeWorktreeAdopt            = "WORKTREE_ADOPT"
	EventCodeSyncSwitchRollback       = "SYNC_SWITCH_ROLLBACK"
	EventCodeSyncSwitchHandoff        = "SYNC_SWITCH_HANDOFF"
	EventCodeMergeConflict            = "MERGE_CONFLICT"
	EventCodeAIMergeResolution        = "AI_MERGE_RESOLUTION"
	EventCodeAIMergeValidation        = "AI_MERGE_VALIDATION"
	EventCodeAIMergeRollback          = "AI_MERGE_ROLLBACK"
	EventCodeAIMergeHandoff           = "AI_MERGE_HANDOFF"
	EventCodeStashConflict            = "STASH_CONFLICT"
	EventCodeAIStashResolution        = "AI_STASH_RESOLUTION"
	EventCodeAIStashValidation        = "AI_STASH_VALIDATION"
	EventCodeAIStashHandoff           = "AI_STASH_HANDOFF"
	EventCodeNamespacePlan            = "NAMESPACE_PLAN"
	EventCodeNamespaceApply           = "NAMESPACE_APPLY"
	EventCodeNamespaceSkip            = "NAMESPACE_SKIP"
	EventCodeNamespaceNoop            = "NAMESPACE_NOOP"
	EventCodeNamespaceError           = "NAMESPACE_ERROR"
	EventCodeRemotePlan               = "REMOTE_PLAN"
	EventCodeRemoteSkip               = "REMOTE_SKIP"
	EventCodeRemoteUpdate             = "REMOTE_UPDATE"
	EventCodeRemoteMissing            = "REMOTE_MISSING"
	EventCodeRemoteDeclined           = "REMOTE_DECLINED"
	EventCodeProtocolPlan             = "PROTOCOL_PLAN"
	EventCodeProtocolSkip             = "PROTOCOL_SKIP"
	EventCodeProtocolUpdate           = "PROTOCOL_UPDATE"
	EventCodeProtocolDeclined         = "PROTOCOL_DECLINED"
	EventCodeTaskPlan                 = "TASK_PLAN"
	EventCodeTaskApply                = "TASK_APPLY"
	EventCodeTaskSkip                 = "TASK_SKIP"
	EventCodeTaskError                = "TASK_ERROR"
	EventCodeFolderPlan               = "REPO_FOLDER_PLAN"
	EventCodeFolderSkip               = "REPO_FOLDER_SKIP"
	EventCodeFolderRename             = "REPO_FOLDER_RENAME"
	EventCodeFolderError              = "REPO_FOLDER_ERROR"
	EventCodeWorkflowOperationSuccess = "WORKFLOW_OPERATION_SUCCESS"
	EventCodeWorkflowOperationFailure = "WORKFLOW_OPERATION_FAILURE"
	EventCodeWorkflowStepSummary      = "WORKFLOW_STEP_SUMMARY"
)
