package shared

// Event code catalogue shared across repository executors and workflow logging.
const (
	EventCodeRepoSwitched             = "REPO_SWITCHED"
	EventCodeRepoDirty                = "REPO_DIRTY"
	EventCodeNamespacePlan            = "NAMESPACE_PLAN"
	EventCodeNamespaceApply           = "NAMESPACE_APPLY"
	EventCodeNamespaceSkip            = "NAMESPACE_SKIP"
	EventCodeNamespaceNoop            = "NAMESPACE_NOOP"
	EventCodeNamespaceError           = "NAMESPACE_ERROR"
	EventCodeRemotePlan               = "REMOTE_PLAN"
	EventCodeRemoteSkip               = "REMOTE_SKIP"
	EventCodeRemoteUpdate             = "REMOTE_UPDATE"
	EventCodeRemoteMissing            = "REMOTE_MISSING"
	EventCodeRemoteDeclined           = "REMOTE_DECLINED"
	EventCodeProtocolPlan             = "PROTOCOL_PLAN"
	EventCodeProtocolSkip             = "PROTOCOL_SKIP"
	EventCodeProtocolUpdate           = "PROTOCOL_UPDATE"
	EventCodeProtocolDeclined         = "PROTOCOL_DECLINED"
	EventCodeTaskPlan                 = "TASK_PLAN"
	EventCodeTaskApply                = "TASK_APPLY"
	EventCodeTaskSkip                 = "TASK_SKIP"
	EventCodeTaskError                = "TASK_ERROR"
	EventCodeFolderPlan               = "REPO_FOLDER_PLAN"
	EventCodeFolderSkip               = "REPO_FOLDER_SKIP"
	EventCodeFolderRename             = "REPO_FOLDER_RENAME"
	EventCodeFolderError              = "REPO_FOLDER_ERROR"
	EventCodeWorkflowOperationSuccess = "WORKFLOW_OPERATION_SUCCESS"
	EventCodeWorkflowOperationFailure = "WORKFLOW_OPERATION_FAILURE"
)
